tap "can1357/tap"
tap "finestructure/tap"
tap "grishka/grishka"
tap "homebrew-ffmpeg/ffmpeg", trusted: true
tap "jetbrains/junie", trusted: true
tap "jundot/omlx", "https://github.com/jundot/omlx"
tap "nikitabobko/tap"
# Swiss-army knife for Android testing and development
brew "adb-enhanced"
# American Fuzzy Lop++
brew "afl++"
# Tool for reverse engineering 3rd party, closed, binary Android apps
brew "apktool"
# Tool for generating GNU Standards-compliant Makefiles
brew "automake"
# Clone of cat(1) with syntax highlighting and Git integration
brew "bat"
# Backend processor for BibLaTeX
brew "biber"
# Object-file caching compiler wrapper
brew "ccache"
# Anti-virus software
brew "clamav"
# Formatting tools for C, C++, Obj-C, Java, JavaScript, TypeScript
brew "clang-format"
# Cross-platform make
brew "cmake"
# Documentation for CMake
brew "cmake-docs"
# Dependency manager for Cocoa projects
brew "cocoapods"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Static analysis of C and C++ code
brew "cppcheck"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# USB programmer
brew "dfu-util"
# Load/unload environment variables based on $PWD
brew "direnv"
# .NET Core
brew "dotnet"
# Command-line fuzzy finder written in Go
brew "fzf"
# GNU compiler collection
brew "gcc"
# Git extension for versioning large files
brew "git-lfs"
# Command-driven, interactive function plotting
brew "gnuplot"
# Open source programming language to build simple/reliable/efficient software
brew "go"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle"
# Open-source build automation tool based on the Groovy and Kotlin DSL
brew "gradle@8"
# GNU grep, egrep and fgrep
brew "grep"
# Development framework for multimedia applications
brew "gstreamer"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c@76"
# C/C++ and Java libraries for Unicode and globalization
brew "icu4c@77"
# Tools and libraries to manipulate images in select formats
brew "imagemagick"
# Install and debug iPhone apps from the command-line
brew "ios-deploy"
# Sane PBXProj files
brew "kin"
# Anti-bikeshedding Kotlin linter with built-in formatter
brew "ktlint"
# Simple terminal UI for git commands
brew "lazygit"
# Sophisticated file transfer program
brew "lftp"
# Postgres C API library
brew "libpq", link: true
# LTeX+ Language Server: maintained fork of LTeX Language Server
brew "ltex-ls-plus"
# Utility for directing compilation
brew "make"
# Command-line utility to communicate with ModBus slave (RTU or TCP)
brew "mbpoll"
# Simple tool to make locally trusted development certificates
brew "mkcert"
# Message broker implementing the MQTT protocol
brew "mosquitto"
# Open source relational database management system
brew "mysql-client"
# Ambitious Vim-fork focused on extensibility and agility
brew "neovim"
# Small build system for use with gyp or CMake
brew "ninja"
# Port scanning utility for large networks
brew "nmap"
# Open-source, cross-platform JavaScript runtime environment
brew "node"
# Open-source, cross-platform JavaScript runtime environment
brew "node@24"
# Libraries for security-enabled client and server applications
brew "nss"
# Development kit for the Java programming language
brew "openjdk@17"
# Tools and libraries for smart cards
brew "opensc"
# OpenBSD freely-licensed SSH connectivity tools
brew "openssh"
# Cryptography and SSL/TLS Toolkit
brew "openssl@1.1"
# Minimal dumb-terminal emulation program
brew "picocom"
# Draw UML diagrams
brew "plantuml"
# Generate podman quadlet files from a podman command or compose file
brew "podlet"
# Alternative to docker-compose using podman
brew "podman-compose"
# Sound system for POSIX OSes
brew "pulseaudio"
# Generic machine emulator and virtualizer
brew "qemu"
# Search tool like grep and The Silver Searcher
brew "ripgrep"
# Powerful, clean, object-oriented scripting language
brew "ruby@3.3"
# Display and control your Android device
brew "scrcpy"
# 7-Zip is a file archiver with a high compression ratio
brew "sevenzip"
# Shell Script Compiler
brew "shc"
# Static analysis and lint tool, for (ba)sh scripts
brew "shellcheck"
# Work with remote images registries
brew "skopeo"
# SOcket CAT: netcat on steroids
brew "socat"
# Audio processing library
brew "sound-touch"
# Cross-shell prompt for astronauts
brew "starship"
# Tool to enforce Swift style and conventions
brew "swiftlint"
# Easiest, most secure way to use WireGuard and 2FA
brew "tailscale"
# User interface to the TELNET protocol
brew "telnet"
# Programmatically correct mistyped console commands
brew "thefuck"
# Display directories as trees (with optional color/HTML output)
brew "tree"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Internet file retriever
brew "wget"
# JavaScript package manager
brew "yarn"
# Tool for managing your YubiKey configuration
brew "ykman"
# Command-line tool for the YubiKey PIV application
brew "yubico-piv-tool"
# General-purpose lossless data-compression library
brew "zlib"
# Real-time type-ahead completion for Zsh
brew "zsh-autocomplete"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Android SDK component
cask "android-platform-tools"
# Electronics prototyping platform
cask "arduino-ide"
# Utility improving 3rd party mouse performance and functionalities
cask "bettermouse"
# Web security testing toolkit
cask "burp-suite"
# Slicer and cloud services for some Creality FDM 3D printers
cask "creality-print"
# Visually compare and merge files
cask "diffmerge"
# Collaborative team software
cask "figma"
# Web browser
cask "firefox"
# 3D parametric modeller
cask "freecad"
# Web browser
cask "google-chrome"
# Hex editor for reverse engineers
cask "imhex"
# JetBrains tools manager
cask "jetbrains-toolbox"
# GPU-based terminal emulator
cask "kitty"
# Connect to your Android devices
cask "macdroid"
# Full TeX Live distribution with GUI applications
cask "mactex"
# Mesh processing system
cask "meshlab"
cask "mqtt-explorer"
# Desktop sync client for Nextcloud software products
cask "nextcloud-vfs"
# Command-line tools for Nordic nRF Semiconductors
cask "nordic-nrf-command-line-tools"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Collaboration platform for API development
cask "postman"
# Client for Proton Drive
cask "proton-drive"
# Bridges Proton Mail to email clients supporting IMAP and SMTP protocols
cask "proton-mail-bridge"
# VPN client focusing on security
cask "protonvpn"
# HTTP debugging proxy
cask "proxyman"
# G-code generator for 3D printers (RepRap, Makerbot, Ultimaker etc.)
cask "prusaslicer"
# Imaging utility to install operating systems to a microSD card
cask "raspberry-pi-imager"
# Control your tools with a few keystrokes
cask "raycast"
# Software and Documentation pack for Segger J-Link debug probes
cask "segger-jlink"
# Software and Documentation pack for Segger Ozone J-Link debugger
cask "segger-ozone"
# Team communication and collaboration software
cask "slack"
# Music streaming service
cask "spotify"
# Mesh VPN based on WireGuard
cask "tailscale-app"
# JDK from the Eclipse Foundation (Adoptium)
cask "temurin@8"
# LaTeX editor
cask "texifier"
# Customizable email client
cask "thunderbird"
# Multimedia player
cask "vlc"
# Binary releases of VS Code without MS branding/telemetry/licensing
cask "vscodium"
# Network protocol analyzer
cask "wireshark-app"
# Collect, organise, cite, and share research sources
cask "zotero"
vscode "anweber.vscode-httpyac"
vscode "davidanson.vscode-markdownlint"
vscode "ddorch.codium-devcontainer"
vscode "dreamcatcher45.podmanager"
vscode "efoerster.texlab"
vscode "esbenp.prettier-vscode"
vscode "espressif.esp-idf-extension"
vscode "foxundermoon.shell-format"
vscode "hangxingliu.vscode-systemd-support"
vscode "james-yu.latex-workshop"
vscode "jeanp413.open-remote-ssh"
vscode "jebbs.plantuml"
vscode "jeff-hykin.better-shellscript-syntax"
vscode "jeffersonqin.latex-snippets-jeff"
vscode "llvm-vs-code-extensions.vscode-clangd"
vscode "lordimmaculate.platformio-ide"
vscode "ltex-plus.vscode-ltex-plus"
vscode "mads-hartmann.bash-ide-vscode"
vscode "mjpvs.latex-previewer"
vscode "ms-azuretools.vscode-containers"
vscode "ms-azuretools.vscode-docker"
vscode "ms-python.python"
vscode "ms-python.vscode-python-envs"
vscode "ms-vscode.cmake-tools"
vscode "ms-vscode.hexeditor"
vscode "phil294.git-log--graph"
vscode "philosowaffle.openapi-designer"
vscode "pinage404.bash-extension-pack"
vscode "redhat.vscode-xml"
vscode "repreng.csv"
vscode "rpinski.shebang-snippets"
vscode "shd101wyy.markdown-preview-enhanced"
vscode "sndst00m.vscode-native-svg-preview"
vscode "solomonkinard.compare-text"
vscode "sr-team.clang-tidy-sr-team-fork"
vscode "tecosaur.latex-utilities"
vscode "timonwong.shellcheck"
vscode "torn4dom4n.latex-support"
vscode "waderyan.gitblame"
vscode "yzhang.markdown-all-in-one"
